---
- name: R1soft Agent Installation 
  hosts: all
  become: true
  become_method: sudo
  user: centos  
  tasks:
  - name: Create repo
    copy:
      src: r1soft.repo
      dest: /etc/yum.repos.d/


  - name: Install agent
    package:
      name: serverbackup-enterprise-agent
      state: installed



  - name: Start agent
    service:
      name: cdp-agent
      state: restarted
      enabled: true


  - name: Stop iptables
    service:
      name: iptables
      state: stopped
      enabled: false


  - name: Get Key
    shell: "r1soft-setup --get-key http://18.132.37.218/" 

    
         

